### ISSUE TITLE
Riker crashes when trying to relink a non-tmpfile

### ISSUE THREAD

**Issue by ericzty** [curtsinger-lab/riker#45]
In `rkr/data/Trace.cc`, if O_TMPFILE failed, the code makes a tempfile and then unlinks it, but I don't think you can relink a non-O_TMPFILE outside of debugfs. So when O_TMPFILE fails, riker will crash with ENOENT as the linkat() call fails.  (for context, o_tmpfile fails in overlayfs)

https://github.com/curtsinger-lab/riker/blob/bb7cfac5148e646555829c6ef6c585ee618cd9f2/src/rkr/data/Trace.cc#L92-L99

Crash happens here
https://github.com/curtsinger-lab/riker/blob/bb7cfac5148e646555829c6ef6c585ee618cd9f2/src/rkr/data/Trace.cc#L350

Suggested fix: comment out the following lines.

https://github.com/curtsinger-lab/riker/blob/bb7cfac5148e646555829c6ef6c585ee618cd9f2/src/rkr/data/Trace.cc#L91-L94

If you wish, I can make a simple PR to fix this.

**Comment by ccurtsinger** [comment]
I'd be happy to accept a PR for this. Thanks!
