### ISSUE TITLE
Releases with Linux binaries in tarball

### ISSUE THREAD

**Issue by drudru** [curtsinger-lab/riker#49]
Hi, would it be possible to have binaries for 64 bit Linux in a tar ball when you do a release?

I would like to try out Riker, but I don’t use docker. This would really lower the barrier for first-time users.

I kind of like how even the nodejs project provides these.

**Comment by drudru** [comment]
a quick update. I did install it by building it.

**Comment by ccurtsinger** [comment]
This is definitely something we can do when Riker is in a stable state. At this point we likely have many portability issues (e.g. Linux kernel version, architectural differences in syscall behavior, etc.). Building locally and running tests helps to work around some of these or at least detect them, so distributing pre-built binaries would likely make the situation worse.

For now, building Riker shouldn't be too bad. The `Makefile` is what we use during normal development, and you can also run the `Rikerfile` in the root of the project if you're somehow on a system without `make`.
