### ISSUE TITLE
Riker constantly updates target files even though no commands have run

### ISSUE THREAD

**Issue by drudru** [curtsinger-lab/riker#52]
I run 'rkr --show' for a build.
No commands run.
However, the files in my target directory are modified every time.
If nothing runs, nothing should change.

I have a separate riker project that depends on these files.
As a result of these changes, the commands are run every time.

I will look into the code to see why this is happening.

**Comment by ccurtsinger** [comment]
Riker commits all of the build's effects to the filesystem after each build, even if nothing runs. We could add a check to commit only if a matching file is not in place already, but maybe it would be better to commit and set timestamps to avoid all the extra file hashing. I'll look into this.
